### ISSUE TITLE
请问如何删除ocserv？

### ISSUE THREAD

**Issue by aglent** [travislee8964/Ocserv-install-script-for-CentOS-RHEL-7#15]
哪位知道？

**Comment by travislee8964** [comment]
rm -rf /usr/local/sbin/ocserv /usr/local/bin/occtl /usr/lib/systemd/system/ocserv.service /etc/ocserv /usr/local/etc/ocserv /usr/local/share/man/man8/ocserv.8 /usr/local/share/man/man8/occtl.8
