### ISSUE TITLE
请问如何注释掉所有route

### ISSUE THREAD

**Issue by Dennypalace** [travislee8964/Ocserv-install-script-for-CentOS-RHEL-7#19]
刚接触这个，就麻烦问一下，具体怎样注释掉所有route，想改为全局方式，谢谢。

**Comment by travislee8964** [comment]
ocserv.conf 里 route 开头的全部注释，再重启 ocserv 即可。

**Comment by GreatFireWall** [comment]
你好, 注释掉所有 route, 重启ovserv, 所有网站都打不开了.
