### ISSUE TITLE
ocserv-0.10.4.tar.xz 无法下载

### ISSUE THREAD

**Issue by frankwei98** [travislee8964/Ocserv-install-script-for-CentOS-RHEL-7#20]
--2015-09-23 13:19:04--  ftp://ftp.infradead.org/pub/ocserv/ocserv-0.10.4.tar.xz
  (try: 8) => ‘ocserv-0.10.4.tar.xz’
Connecting to ftp.infradead.org (ftp.infradead.org)|2001:770:15f::2|:21... failed: Connection timed out.
Connecting to ftp.infradead.org (ftp.infradead.org)|85.118.1.10|:21... failed: Connection timed out.
Retrying.

一直这样无限循环 能不能把包放在github上 这样比较稳定
谢谢

**Comment by fangshili** [comment]
+1 infradead的DNS总出问题

**Comment by travislee8964** [comment]
更新了，改从 github 下载，github 的 repository 也是原作者维护。
